### PR TITLE
Add language= parameter to API queries

### LINKED ISSUE #27: Values are not delivered in configured language - only english
Hi, the actual script is only transfering the values in english. If I have setup my config for "de-DE" still the transmitted data to MQTT-Gateway is in english (like Device typ Oven instead of Backofen).

**Miele API offers the language setting:**
curl -H "Accept:text/event-stream" -H "Accept-Language: {{de-DE||en-GB}}" -H "Authorization: Bearer {{access_token}}" https://api.mcs3.miele.com/v1/devices/all/events

[Quelle: https://www.miele.com/developer/eventing.html]

It would be good if the script could use the accepted language value to transmit values in configured language.

### PR DESCRIPTION
**Pull request by christianTF**
- Read language from the country variable
- Send language= parameter on API queries

This closes #27

### CODE REVIEW

**Comment by oklona** [comment]
The language - commit is easy to approve of. I normally don't like the short-form if-statements ( if x ? a:b ) as I find them less readable for "the general public", but it does make sense to use them. I am more concerned about the second commit, with the quotes. I probably added quotes for some reason at one point, but this might be historical, since I used to pass it to command-line mosquitto_pub instead of using the current phpMQTT by BlueRhinos. I will test by just removing the quotes entirely.

**Comment by oklona** [comment]
So, if you could remove the quotes-commit from the PR, I will approve :-) -And then I will just remove the quotes entirely to make the code as clean as possible.

**Comment by christianTF** [comment]
No idea how to remove one of two commits in a pull request 🤪 
I‘ll try this after work 🙂

I did some further testing on how to remove the token request in the middle of the wizard, and auto-fill them on start (without wizard), if all required params are in the config. This took some major changes, therefore I won’t push that.

**Comment by oklona** [comment]
Haha, no problem! I will just approve as it is then, and shortly after, make a new change with just removing the quotes.

**Pull request merged**
